# for local development
version: '3.7'
services:
  frontend:
    container_name: nuxt
    build:
      context: .
#      dockerfile: Dockerfile
      target: 'develop-stage'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules/'
    command: ['npm', 'run', 'dev']
#    environment:
#      - CHOKIDAR_USEPOLLING=true
